/*
Jakub Wawak
kubawawak@gmail.com
all rights reseved
 */
package com.jakubwawak.ui_maintenance;

import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JTextField;
import javax.swing.table.TableModel;
import utils.Profile;
import utils.Profile_Engine;

/**
 *Window for creating new profiles
 * @author kubaw
 */
public class new_profile_window extends javax.swing.JDialog {

    /**
     * Creates new form new_profile_window
     */
    Profile_Engine profile_engine;
    public new_profile_window(javax.swing.JDialog parent, boolean modal,Profile_Engine profile_engine) {
        super(parent, modal);
        this.profile_engine = profile_engine;
        initComponents();
        this.setLocationRelativeTo(null);
        setVisible(true);
    }
    
    
    /**
     * Function for getting table data
     * @return ArrayList
     */
    ArrayList<String> get_table_data(){
        ArrayList<String> data = new ArrayList<>();
        TableModel model = table_notes.getModel();
        data.add((String) model.getValueAt(0, 0));
        data.add((String) model.getValueAt(0, 1));
        data.add((String) model.getValueAt(0, 2));
        return data;
    }
    
    
    /**
     * Function for validate fields
     * @param object
     * @return boolean
     */
    boolean validate_field(JTextField object){
        return !object.getText().equals("");
    }
    
    /**
     * Function for validate all compontents
     * @return boolean
     */
    boolean validate_fields(){
        return validate_field(field_name) && validate_field(field_url) && validate_field(field_endpoint);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_notes = new javax.swing.JTable();
        button_create = new javax.swing.JButton();
        field_name = new javax.swing.JTextField();
        field_url = new javax.swing.JTextField();
        field_endpoint = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Profile creator");

        jLabel1.setText("Name:");

        jLabel2.setText("URL:");

        jLabel3.setText("Endpoint for health check:");

        jLabel4.setText("Key words / notes");

        table_notes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Note 1", "Note 2", "Note 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_notes);
        if (table_notes.getColumnModel().getColumnCount() > 0) {
            table_notes.getColumnModel().getColumn(0).setResizable(false);
            table_notes.getColumnModel().getColumn(1).setResizable(false);
            table_notes.getColumnModel().getColumn(2).setResizable(false);
        }

        button_create.setText("Create new profile");
        button_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_createActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(button_create, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 139, Short.MAX_VALUE))
                            .addComponent(field_name)
                            .addComponent(field_url)
                            .addComponent(field_endpoint))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(field_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(field_url, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(field_endpoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_create)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_createActionPerformed
        if ( validate_fields() ){
            Profile profile = new Profile();
            profile.profile_name = field_name.getText();
            profile.profile_url = field_url.getText();
            profile.profile_health_connection_url = field_endpoint.getText();
            profile.profile_special_data = get_table_data();
            try {
                profile_engine.add_profile(profile);
                new message_window(this,true,"Profile added","");
                dispose();
            } catch (IOException ex) {
                new message_window(this,true,"Error\n"+ex.toString(),"ERROR");
            }
        }
        else{
            new message_window(this,true,"Failed to load fields. Check fields.","");
        }
    }//GEN-LAST:event_button_createActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_create;
    private javax.swing.JTextField field_endpoint;
    private javax.swing.JTextField field_name;
    private javax.swing.JTextField field_url;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_notes;
    // End of variables declaration//GEN-END:variables
}
