/*
Jakub Wawak
kubawawak@gmail.com
all rights reseved
 */
package com.jakubwawak.ui_maintenance;
import javax.swing.DefaultListModel;
import utils.Profile;
import utils.Profile_Engine;

/**
 * Window for picking profile
 * @author kubaw
 */
public class profile_picker_window extends javax.swing.JDialog {

    /**
     * Creates new form profile_picker_window
     */
    
    Profile_Engine profile_engine;
    
    public profile_picker_window(java.awt.Frame parent, boolean modal,Profile_Engine profiles) {
        super(parent, modal);
        this.profile_engine = profiles;
        initComponents();
        this.setLocationRelativeTo(null);
        load_window();
        setVisible(true);
    }
    
    /**
     * Function for load window components
     */
    void load_window(){
        load_list();
    }
    
    /**
     * Function for loading list objects
     */
    void load_list(){
        DefaultListModel dlm = new DefaultListModel();
        dlm.addElement("0:Empty profile");
        if (profile_engine.list_profiles.size() > 0){
            for(Profile profile : profile_engine.list_profiles){
                dlm.addElement(profile.profile_name);
            }
        }
        list_profiles.setModel(dlm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list_profiles = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_profiles = new javax.swing.JMenu();
        menu_createnewprofile = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Profile picker");

        list_profiles.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(list_profiles);

        jButton1.setText("Set profile");

        menu_profiles.setText("Profiles");

        menu_createnewprofile.setText("Create new profile");
        menu_createnewprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_createnewprofileActionPerformed(evt);
            }
        });
        menu_profiles.add(menu_createnewprofile);

        jMenuBar1.add(menu_profiles);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_createnewprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_createnewprofileActionPerformed
        new new_profile_window(this,true,profile_engine);
    }//GEN-LAST:event_menu_createnewprofileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list_profiles;
    private javax.swing.JMenuItem menu_createnewprofile;
    private javax.swing.JMenu menu_profiles;
    // End of variables declaration//GEN-END:variables
}
