/*
Jakub Wawak
kubawawak@gmail.com
all rights reseved
 */
package com.jakubwawak.ui_maintenance;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import utils.Request_History_Object;

/**
 *Window for presenting request history
 * @author kubaw
 */
public class response_history_window extends javax.swing.JDialog {

    /**
     * Creates new form response_history_window
     */
    ArrayList<Request_History_Object> history;
    
    public response_history_window(java.awt.Frame parent, boolean modal,ArrayList<Request_History_Object> history) {
        super(parent, modal);
        this.history = history;
        initComponents();
        load_window();
        this.setLocationRelativeTo(null);
        setVisible(true);
    }
    
    /**
     * Function for loading window content
     */
    void load_window(){
        DefaultListModel dlm = new DefaultListModel();
        for(Request_History_Object rho : history){
            dlm.addElement(rho.show_glance());
        }
        if ( dlm.isEmpty() ){
            dlm.addElement("Empty");
        }
        list_history.setModel(dlm);
        field_rawdata.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list_history = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        field_rawdata = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        label_urlrequest = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Request history");

        list_history.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list_history.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_historyMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(list_history);

        field_rawdata.setColumns(20);
        field_rawdata.setRows(5);
        jScrollPane2.setViewportView(field_rawdata);

        jLabel1.setText("Raw data");

        label_urlrequest.setText("URL request: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_urlrequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(7, 7, 7)
                        .addComponent(label_urlrequest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void list_historyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_historyMouseClicked
        label_urlrequest.setText("URL request: ");
        String selected = list_history.getSelectedValue().toString();
        if (!selected.equals("Empty")){
            int index = list_history.getSelectedIndex();
            label_urlrequest.setText("URL: "+history.get(index).url);
            field_rawdata.setText(history.get(index).raw_response);
            
            if ( label_urlrequest.getText().equals("URL request: ")){
                label_urlrequest.setText("URL request not found");
            }
        }
    }//GEN-LAST:event_list_historyMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea field_rawdata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_urlrequest;
    private javax.swing.JList<String> list_history;
    // End of variables declaration//GEN-END:variables
}
